name: Semgrep Scan

on:
  workflow_call:
    secrets:
      SEMGREP_API_TOKEN:
        required: true
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  semgrep:
    name: Run Semgrep
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Install Semgrep
      - name: Install Semgrep
        run: pip install semgrep

      # Step 3: Run Semgrep with multiple configurations
      - name: Run Semgrep Scans p/ci
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_API_TOKEN }}
        run: semgrep --config p/ci --json > semgrep-ci-results.json

      - name: Save Semgrep Scans p/secrets
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_API_TOKEN }}
        run: semgrep --config p/secrets --json > semgrep-secrets-results.json

      - name: Save Semgrep Scans p/security-audit
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_API_TOKEN }}
        run: semgrep --config p/security-audit --json > semgrep-security-audit-results.json

      - name: Save Semgrep Scans p/docker
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_API_TOKEN }}
        run: semgrep --config p/docker --json > semgrep-docker-results.json

      # Step 4: Upload the results as artifacts
      - name: Upload Semgrep results as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Semgrep-Scan
          path: |
            semgrep-ci-results.json
            semgrep-secrets-results.json
            semgrep-security-audit-results.json
            semgrep-docker-results.json
