name: Semgrep Scan

on:
  workflow_call:
    secrets:
      SEMGREP_API_TOKEN:
        required: true
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  semgrep:
    name: Run Semgrep
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Install Semgrep
      - name: Install Semgrep
        run: pip install semgrep

      # Step 3: Run Semgrep with multiple configurations
      - name: Run Semgrep Scans p/ci
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_API_TOKEN }}
        run: |
          semgrep --config p/ci 

      - name: Save Semgrep Scans p/secrets
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_API_TOKEN }}
        run: semgrep --config p/secrets

      - name: Save Semgrep Scans p/security-audit
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_API_TOKEN }}
        run: semgrep --config p/security-audit

      - name: Save Semgrep Scans p/docker
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_API_TOKEN }}
        run: semgrep --config p/docker

